configure_requires "Alien::Build", "1.19";
configure_requires "Alien::Build::MM", "0.25";
configure_requires "ExtUtils::MakeMaker", "0";
configure_requires "Sort::Versions", "0";
build_requires "HTTP::Tiny", "0.044";
build_requires "IO::Socket::SSL", "1.56";
build_requires "Mozilla::CA", "0";
build_requires "Net::SSLeay", "1.49";
build_requires "URI", "0";
